### ISSUE TITLE
[新功能请求]可以加入nix吗

### ISSUE THREAD

**Issue by a15355447898a** [HougeLangley/archzfs-iso#2]
我希望可以在这个镜像中同时也可以安装NixOS

**Comment by HougeLangley** [comment]
完全没有问题，我来研究下，朋友不要关闭这个 issue ，我晚些时候开始弄 ;)

**Comment by HougeLangley** [comment]
弄好了

**Comment by HougeLangley** [comment]
#[237691d](https://github.com/HougeLangley/archzfs-iso/commit/237691d9b15b5138c17e47caa9a38533430445f6)
